from domain.exceptions.domain_exception import DomainException


class InvalidSecondsException(DomainException):
    pass
